steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-login'
  entrypoint: 'bash'
  args: ['-c', 'echo "$$PASSWORD" | docker login -u "$$USERNAME" --password-stdin']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/react-test', '-f', './client/Dockerfile.dev', './client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-e', 'CI=true', 'odys/react-test', 'npm', 'test']
  id: 'client-test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-client', './client']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-nginx', './nginx']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-server', './server']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-worker', './worker']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'odys/multi-client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'odys/multi-nginx']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'odys/multi-server']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'odys/multi-worker']
availableSecrets:
  secretManager:
  - versionName: projects/837909578112/secrets/DOCKER_PASSWORD/versions/latest
    env: 'PASSWORD'
  - versionName: projects/837909578112/secrets/DOCKER_USERNAME/versions/latest
    env: 'USERNAME'