steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/react-test', '-f', './client/Dockerfile.dev', './client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-e', 'CI=true', 'odys/react-test', 'npm', 'test']
  id: 'client-test'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-client', './client']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-nginx', './nginx']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-server', './server']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/multi-worker', './worker']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-login'
  args: ['login', '--username=$$DOCKER_USERNAME', '--password=$$DOCKER_PASSWORD']
  secretEnv: ['DOCKER_USERNAME', 'DOCKER_PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: ['docker', 'push', 'odys/multi-client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['docker', 'push', 'odys/multi-nginx']
- name: 'gcr.io/cloud-builders/docker'
  args: ['docker', 'push', 'odys/multi-server']
- name: 'gcr.io/cloud-builders/docker'
  args: ['docker', 'push', 'odys/multi-worker']
availableSecrets:
  secretManager:
  - versionName: projects/837909578112/secrets/DOCKER_PASSWORD/versions/1
    env: 'DOCKER_PASSWORD'
  - versionName: projects/837909578112/secrets/DOCKER_USERNAME/versions/1
    env: 'DOCKER_USERNAME'