steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'docker-login'
  entrypoint: 'bash'
  args: ['-c', 'echo "$$PASSWORD" | docker login -u "$$USERNAME" --password-stdin']
  secretEnv: ['USERNAME', 'PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'odys/react-test', '-f', './client/Dockerfile.dev', './client']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-e', 'CI=true', 'odys/react-test', 'npm', 'test']
  id: 'client-test'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t "$$USERNAME"/multi-client ./client']
  secretEnv: ['USERNAME']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t "$$USERNAME"/multi-nginx ./nginx']
  secretEnv: ['USERNAME']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t "$$USERNAME"/multi-server ./server']
  secretEnv: ['USERNAME']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t "$$USERNAME"/multi-worker ./worker']
  secretEnv: ['USERNAME']
  waitFor: ['client-test']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push "$$USERNAME"/multi-client']
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push "$$USERNAME"/multi-nginx']
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push "$$USERNAME"/multi-server']
  secretEnv: ['USERNAME']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push "$$USERNAME"/multi-worker']
  secretEnv: ['USERNAME']
availableSecrets:
  secretManager:
  - versionName: projects/837909578112/secrets/DOCKER_PASSWORD/versions/latest
    env: 'PASSWORD'
  - versionName: projects/837909578112/secrets/DOCKER_USERNAME/versions/latest
    env: 'USERNAME'